// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SpanreedMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CloseConnection struct {
	_tab flatbuffers.Table
}

func GetRootAsCloseConnection(buf []byte, offset flatbuffers.UOffsetT) *CloseConnection {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CloseConnection{}
	x.Init(buf, n+offset)
	return x
}

func FinishCloseConnectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCloseConnection(buf []byte, offset flatbuffers.UOffsetT) *CloseConnection {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CloseConnection{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCloseConnectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CloseConnection) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CloseConnection) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CloseConnection) ClientId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CloseConnection) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *CloseConnection) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CloseConnectionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CloseConnectionAddClientId(builder *flatbuffers.Builder, clientId uint32) {
	builder.PrependUint32Slot(0, clientId, 0)
}
func CloseConnectionAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reason), 0)
}
func CloseConnectionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
