// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SpanreedMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DestinationMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsDestinationMessage(buf []byte, offset flatbuffers.UOffsetT) *DestinationMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DestinationMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishDestinationMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDestinationMessage(buf []byte, offset flatbuffers.UOffsetT) *DestinationMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DestinationMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDestinationMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DestinationMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DestinationMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DestinationMessage) MsgType() InnerMsg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return InnerMsg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DestinationMessage) MutateMsgType(n InnerMsg) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *DestinationMessage) Msg(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *DestinationMessage) AppData(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DestinationMessage) AppDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DestinationMessage) AppDataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DestinationMessage) MutateAppData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func DestinationMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DestinationMessageAddMsgType(builder *flatbuffers.Builder, msgType InnerMsg) {
	builder.PrependByteSlot(0, byte(msgType), 0)
}
func DestinationMessageAddMsg(builder *flatbuffers.Builder, msg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(msg), 0)
}
func DestinationMessageAddAppData(builder *flatbuffers.Builder, appData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(appData), 0)
}
func DestinationMessageStartAppDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DestinationMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
