// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SpanreedMessage

import "strconv"

type InnerMsg byte

const (
	InnerMsgNONE              InnerMsg = 0
	InnerMsgProxyMessage      InnerMsg = 1
	InnerMsgConnectionVerdict InnerMsg = 2
)

var EnumNamesInnerMsg = map[InnerMsg]string{
	InnerMsgNONE:              "NONE",
	InnerMsgProxyMessage:      "ProxyMessage",
	InnerMsgConnectionVerdict: "ConnectionVerdict",
}

var EnumValuesInnerMsg = map[string]InnerMsg{
	"NONE":              InnerMsgNONE,
	"ProxyMessage":      InnerMsgProxyMessage,
	"ConnectionVerdict": InnerMsgConnectionVerdict,
}

func (v InnerMsg) String() string {
	if s, ok := EnumNamesInnerMsg[v]; ok {
		return s
	}
	return "InnerMsg(" + strconv.FormatInt(int64(v), 10) + ")"
}
