// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SpanreedMessage

import "strconv"

type ProxyDestInnerMsg byte

const (
	ProxyDestInnerMsgNONE                       ProxyDestInnerMsg = 0
	ProxyDestInnerMsgProxyDestConnectionRequest ProxyDestInnerMsg = 1
	ProxyDestInnerMsgProxyDestClientMessage     ProxyDestInnerMsg = 2
	ProxyDestInnerMsgProxyDestCloseConnection   ProxyDestInnerMsg = 3
)

var EnumNamesProxyDestInnerMsg = map[ProxyDestInnerMsg]string{
	ProxyDestInnerMsgNONE:                       "NONE",
	ProxyDestInnerMsgProxyDestConnectionRequest: "ProxyDestConnectionRequest",
	ProxyDestInnerMsgProxyDestClientMessage:     "ProxyDestClientMessage",
	ProxyDestInnerMsgProxyDestCloseConnection:   "ProxyDestCloseConnection",
}

var EnumValuesProxyDestInnerMsg = map[string]ProxyDestInnerMsg{
	"NONE":                       ProxyDestInnerMsgNONE,
	"ProxyDestConnectionRequest": ProxyDestInnerMsgProxyDestConnectionRequest,
	"ProxyDestClientMessage":     ProxyDestInnerMsgProxyDestClientMessage,
	"ProxyDestCloseConnection":   ProxyDestInnerMsgProxyDestCloseConnection,
}

func (v ProxyDestInnerMsg) String() string {
	if s, ok := EnumNamesProxyDestInnerMsg[v]; ok {
		return s
	}
	return "ProxyDestInnerMsg(" + strconv.FormatInt(int64(v), 10) + ")"
}
