// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SpanreedMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProxyDestCloseConnection struct {
	_tab flatbuffers.Table
}

func GetRootAsProxyDestCloseConnection(buf []byte, offset flatbuffers.UOffsetT) *ProxyDestCloseConnection {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProxyDestCloseConnection{}
	x.Init(buf, n+offset)
	return x
}

func FinishProxyDestCloseConnectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProxyDestCloseConnection(buf []byte, offset flatbuffers.UOffsetT) *ProxyDestCloseConnection {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProxyDestCloseConnection{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProxyDestCloseConnectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProxyDestCloseConnection) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProxyDestCloseConnection) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProxyDestCloseConnection) ClientId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProxyDestCloseConnection) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func ProxyDestCloseConnectionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ProxyDestCloseConnectionAddClientId(builder *flatbuffers.Builder, clientId uint32) {
	builder.PrependUint32Slot(0, clientId, 0)
}
func ProxyDestCloseConnectionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
