// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SpanreedMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProxyDestConnectionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsProxyDestConnectionRequest(buf []byte, offset flatbuffers.UOffsetT) *ProxyDestConnectionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProxyDestConnectionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishProxyDestConnectionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProxyDestConnectionRequest(buf []byte, offset flatbuffers.UOffsetT) *ProxyDestConnectionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProxyDestConnectionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProxyDestConnectionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProxyDestConnectionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProxyDestConnectionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProxyDestConnectionRequest) ClientId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProxyDestConnectionRequest) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func ProxyDestConnectionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ProxyDestConnectionRequestAddClientId(builder *flatbuffers.Builder, clientId uint32) {
	builder.PrependUint32Slot(0, clientId, 0)
}
func ProxyDestConnectionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
